name: BitRot Nuke Previous Runs

on:
  workflow_dispatch:

concurrency:
  group: bot-single-instance
  cancel-in-progress: true

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cancelling any previous runs in this group..."
